### PR TITLE
Fixed android generator assignment

### PR DESCRIPTION
**Pull request by omatrot**
This is related to #87 
The generator is now properly instantiated and will run.

### CODE REVIEW

**Comment by dansiegel** [comment]
Thanks for the catch @omatrot I actually haven't gotten to testing this specific functionality yet. Please let me know if this resolves issue #87 for you.

**Comment by omatrot** [comment]
I'll try as soon as a new nuget is available.

**Comment by dansiegel** [comment]
one thing to keep in mind is that it looks like you were testing with 1.4, master is radically different particularly for the TemplateManifests as 2.0 is making a shift to do in-place Templated Manifests, where 1.4 had to copy them over.

**Comment by omatrot** [comment]
It is fine by me. However, it seems that some config is needed to upgrade because now I have the following error:
```
/Users/omatrot/Documents/hygeex/etp/etp_proto/packages/Mobile.BuildTools.2.0.0.873-ci/build/ImageResize.targets(5,5): Error: Unhandled error while executing CollectImageAssetsTask (etp_proto)
/Users/omatrot/Documents/hygeex/etp/etp_proto/packages/Mobile.BuildTools.2.0.0.873-ci/build/ImageResize.targets(5,5): Error: Object reference not set to an instance of an object (etp_proto)
```

**Comment by omatrot** [comment]
Well first I had this output for the manifest:
```
_TemplateManifestDebug:
  Checking for Platform Template Configurations to Copy
  SdkShortFrameworkIdentifier: ''
  Prefix: 'Manifest_'
  Token: ''
  ManifestTemplatePath: ''
  ManifestOutputPath: ''
/Users/runner/runners/2.163.1/work/1/s/etp_proto/packages/Mobile.BuildTools.2.0.0.873-ci/build/AndroidManifest.targets(17,5): warning : No value was provided for the Manifest. Unable to process Manifest Tokens [/Users/runner/runners/2.163.1/work/1/s/etp_proto/etp_proto/etp_proto.csproj]
```

I've tried setting values for the ManifestTemplatePath and ManifestOutputPath with no luck so far:

```
_TemplateManifestDebug:
  Checking for Platform Template Configurations to Copy
  SdkShortFrameworkIdentifier: ''
  Prefix: 'Manifest_'
  Token: ''
  ManifestTemplatePath: 'build/AndroidTemplateManifest.xml'
  ManifestOutputPath: 'etp_proto/Properties/AndroidManifest.xml'
/Users/runner/runners/2.163.1/work/1/s/etp_proto/packages/Mobile.BuildTools.2.0.0.873-ci/build/AndroidManifest.targets(17,5): warning : No value was provided for the Manifest. Unable to process Manifest Tokens [/Users/runner/runners/2.163.1/work/1/s/etp_proto/etp_proto/etp_proto.csproj]
```
I have no idea which environment variable to set to solve this problem.

**Pull request merged**
