### PR TITLE
upgrade to dotnet 7

### LINKED ISSUE #334: [.NET 8.0] Build crash System.Security.Permissions missing
# Description

Build crashes with "Could not load file or assembly System.Security.Permissions" .

https://learn.microsoft.com/en-us/dotnet/core/compatibility/extensions/8.0/configurationmanager-package
https://learn.microsoft.com/en-us/dotnet/core/compatibility/8.0#extensions

## Reproduction Steps

1. Install https://github.com/dotnet/core/blob/main/release-notes/8.0/preview/8.0.0-rc.2.md
2. Create .NET 8.0 console project
3. Setup appsettings feature from Mobile.BuildTools
4. Build

## Expected Behavior

Generate app settings class (https://mobilebuildtools.com/config/appsettings/).

## Actual Behavior

```
/Users/runner/.nuget/packages/mobile.buildtools/2.0.245/build/Mobile.BuildTools.targets(37,5): 
error MSB4018: The "LocateBuildToolsConfigTask" task failed unexpectedly. 
[/Users/runner/work/mobile-app/mobile-app/src/Mobile.Business/Mobile.Business.csproj::TargetFramework=net8.0]

/Users/runner/.nuget/packages/mobile.buildtools/2.0.245/build/Mobile.BuildTools.targets(37,5): 
error MSB4018: System.IO.FileNotFoundException: 
Could not load file or assembly 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. 
The system cannot find the file specified. 
[/Users/runner/work/mobile-app/mobile-app/src/Mobile.Business/Mobile.Business.csproj::TargetFramework=net8.0]
```

## Environment

- OS: [OSX]
- IDE: [VSMac|CLI|Rider]
- BuildTools Version: [2.0.245]
- IDE Version: [-]
- Build Target Framework: [MAUI-8.0|NET-8.0]

## Reproduction App

[ConsoleApp1.zip](https://github.com/dansiegel/Mobile.BuildTools/files/12926979/ConsoleApp1.zip)

### PR DESCRIPTION
**Pull request by Px7-941**
fixes #334

### CODE REVIEW

**Comment by dansiegel** [comment]
We will only be updating the master branch as that is what the next release will be off of. If you would like to pull your actual changes into a new branch and push that here we can look at getting it merged.

**Comment by Px7-941** [comment]
@dansiegel Has a Nuget release already been created from the master branch? Maybe a customization is no longer necessary from my side. Unfortunately, I have not yet got the new project structure up and running. The Nuget split does not seem to be completely finished yet.

I'll have to see when I can find some time for this bug, as we have a temporary solution. Until now I had never delved deeper into MSBuild. Wishing you happy holidays.

**Comment by martinimon** [comment]
Hey @Px7-941 @dansiegel  Any luck with this upgrade to dotnet 7 (or dotnet 8 since that has now been released and it LST)?
If not based on the comments of this PR, I'm not quite clear what bug/problem you are having, can you please expand a little more on the issues you're facing. I'm trying to assertain if this is something I could try looking into, or if its potentially better upgrading the main(master) branch from scratch. 

I mainly have interest in upgrading based on #334 , as I'm migrating a Xamarin app into Maui and it is at the stage where it needs to go through the CI pipeline so it can be tested and remidiated (good old feedback loop)
I assume the nuget you attached was based on this branch? If so that sovled my issue, however as you stated not fully tested/completed so other issues might pop up as a result.

**Comment by dansiegel** [comment]
This has been updated to .NET 8

**Pull request closed without merging**
